apiVersion: apps/v1
kind: Deployment
metadata:
  name: perbaikiinaja-backend
  namespace: perbaikiinaja-prod
  labels:
    app: perbaikiinaja-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: perbaikiinaja-backend
  template:
    metadata:
      labels:
        app: perbaikiinaja-backend
    spec:
      containers:
        - name: perbaikiinaja-backend
          image: ${DOCKERHUB_USERNAME}/perbaikiinaja-backend:main
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: perbaikiinaja-config
                  key: PORT
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: perbaikiinaja-config
                  key: SPRING_PROFILES_ACTIVE
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: perbaikiinaja-secrets
                  key: PG_HOST
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: perbaikiinaja-secrets
                  key: PG_USER
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: perbaikiinaja-secrets
                  key: PG_PASS
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: perbaikiinaja-secrets
                  key: JWT_SECRET_KEY
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      imagePullSecrets:
        - name: dockerhub-secret