apiVersion: v1
kind: Service
metadata:
  name: perbaikiinaja-backend-service
  namespace: perbaikiinaja-prod
  labels:
    app: perbaikiinaja-backend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  selector:
    app: perbaikiinaja-backend