name: Spring Boot CI/CD Pipeline with Docker and Kubernetes

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug branch information
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub event name: ${{ github.event_name }}"
          echo "GitHub branch: ${{ github.ref_name }}"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Build and package with Gradle
        run: ./gradlew bootJar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar

  build-and-push-docker:
    needs: build
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/perbaikiinaja-backend:${{ env.BRANCH_NAME }},${{ secrets.DOCKERHUB_USERNAME }}/perbaikiinaja-backend:latest

  deploy-staging:
    needs: build-and-push-docker
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
      - name: Debug branch information
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub event name: ${{ github.event_name }}"
          echo "Is staging branch: ${{ github.ref == 'refs/heads/staging' }}"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup known hosts
        run: |
          mkdir -p ~/.ssh
          echo "Resolving hostname..."
          getent hosts ${{ secrets.EC2_HOST }} || echo "Could not resolve hostname with getent"
          echo "Attempting to scan with ssh-keyscan..."
          ssh-keyscan -v -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || echo "Warning: ssh-keyscan failed"
          cat ~/.ssh/known_hosts

      - name: Deploy to EC2 with Docker (Amazon Linux)
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASS: ${{ secrets.PG_PASS }}
          PORT: ${{ secrets.PORT || '8080' }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          ssh $EC2_USERNAME@$EC2_HOST << EOF
            mkdir -p ~/perbaikiinaja

            # Create docker-compose.yml with environment variable substitution
            cat > ~/perbaikiinaja/docker-compose.yml << 'COMPOSE_EOF'
          version: '3'
          services:
            perbaikiinaja-backend:
              image: ${DOCKERHUB_USERNAME}/perbaikiinaja-backend:staging
              container_name: perbaikiinaja-backend
              restart: always
              ports:
                - "${PORT}:8080"
              environment:
                - PG_HOST=${PG_HOST}
                - PG_USER=${PG_USER}
                - PG_PASS=${PG_PASS}
                - JWT_SECRET_KEY=${JWT_SECRET_KEY}
                - PORT=8080
          COMPOSE_EOF

            # Export environment variables for envsubst
            export PG_HOST="${PG_HOST}"
            export PG_USER="${PG_USER}"
            export PG_PASS="${PG_PASS}"
            export JWT_SECRET_KEY="${JWT_SECRET_KEY}"
            export PORT="${PORT}"
            export DOCKERHUB_USERNAME="${DOCKERHUB_USERNAME}"

            # Substitute environment variables in docker-compose.yml
            cd ~/perbaikiinaja
            envsubst < docker-compose.yml > docker-compose-temp.yml
            mv docker-compose-temp.yml docker-compose.yml

            # Ensure Docker is running
            sudo service docker start

            # Pull the latest image
            docker pull \${DOCKERHUB_USERNAME}/perbaikiinaja-backend:staging

            # Stop and remove existing container
            docker-compose down

            # Start the container
            docker-compose up -d

            # Check if container is running
            sleep 10
            if docker ps --filter "name=perbaikiinaja-backend" --format "{{.Names}}" | grep -q perbaikiinaja-backend; then
              echo "Container is running successfully"
              echo "Application should be accessible at http://${EC2_HOST}:${PORT}"
            else
              echo "Error: Container failed to start"
              docker logs perbaikiinaja-backend
              exit 1
            fi
          EOF

  deploy-production:
    needs: build-and-push-docker
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}

      - name: Setup SSH configuration
        run: |
          mkdir -p ~/.ssh
          
          # Create SSH config to handle host key checking
          cat > ~/.ssh/config << EOF
          Host ${{ secrets.PROD_EC2_HOST }}
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            LogLevel ERROR
          EOF
          
          # Set proper permissions
          chmod 600 ~/.ssh/config
          
          # Test SSH connectivity
          echo "Testing SSH connection to ${{ secrets.PROD_EC2_HOST }}..."
          ssh -o ConnectTimeout=10 ${{ secrets.PROD_EC2_USERNAME }}@${{ secrets.PROD_EC2_HOST }} 'echo "SSH connection successful"' || {
            echo "SSH connection failed. Please check:"
            echo "1. Security group allows SSH (port 22) from 0.0.0.0/0"
            echo "2. SSH service is running on the EC2 instance"
            echo "3. The EC2 instance is running and accessible"
            echo "4. The SSH key is correct"
            exit 1
          }

      - name: Deploy to Production EC2 with Kubernetes
        env:
          PROD_EC2_HOST: ${{ secrets.PROD_EC2_HOST }}
          PROD_EC2_USERNAME: ${{ secrets.PROD_EC2_USERNAME }}
          PROD_PG_HOST: ${{ secrets.PROD_PG_HOST }}
          PROD_PG_USER: ${{ secrets.PROD_PG_USER }}
          PROD_PG_PASS: ${{ secrets.PROD_PG_PASS }}
          PROD_JWT_SECRET_KEY: ${{ secrets.PROD_JWT_SECRET_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          # Copy Kubernetes manifests to production server
          echo "Creating directory on production server..."
          ssh $PROD_EC2_USERNAME@$PROD_EC2_HOST 'mkdir -p ~/perbaikiinaja-k8s'
          
          echo "Copying Kubernetes manifests..."
          scp -r k8s/* $PROD_EC2_USERNAME@$PROD_EC2_HOST:~/perbaikiinaja-k8s/
          
          echo "Deploying to Kubernetes..."
          ssh $PROD_EC2_USERNAME@$PROD_EC2_HOST << 'EOF'
            cd ~/perbaikiinaja-k8s
          
            # Check if kubectl and k3s are working
            echo "Checking Kubernetes cluster status..."
            kubectl cluster-info || {
              echo "Kubernetes cluster not accessible. Checking K3s status..."
              sudo systemctl status k3s
              echo "Attempting to restart K3s..."
              sudo systemctl restart k3s
              sleep 30
              kubectl cluster-info || {
                echo "K3s failed to start. Please check the server manually."
                exit 1
              }
            }
          
            # FIRST: Create namespace
            echo "Creating namespace..."
            kubectl apply -f namespace.yaml
          
            # Wait for namespace to be ready
            sleep 5
          
            # SECOND: Create DockerHub secret for pulling images
            echo "Creating DockerHub secret..."
            kubectl delete secret dockerhub-secret -n perbaikiinaja-prod --ignore-not-found
            kubectl create secret docker-registry dockerhub-secret \
              --docker-server=https://index.docker.io/v1/ \
              --docker-username=${{ secrets.DOCKERHUB_USERNAME }} \
              --docker-password=${{ secrets.DOCKERHUB_TOKEN }} \
              --namespace=perbaikiinaja-prod
          
            # THIRD: Create application secrets
            echo "Creating application secrets..."
            kubectl delete secret perbaikiinaja-secrets -n perbaikiinaja-prod --ignore-not-found
            kubectl create secret generic perbaikiinaja-secrets \
              --from-literal=PG_HOST="${PROD_PG_HOST}" \
              --from-literal=PG_USER="${PROD_PG_USER}" \
              --from-literal=PG_PASS="${PROD_PG_PASS}" \
              --from-literal=JWT_SECRET_KEY="${PROD_JWT_SECRET_KEY}" \
              --namespace=perbaikiinaja-prod
          
            # FOURTH: Apply ConfigMap
            echo "Applying ConfigMap..."
            kubectl apply -f configmap.yaml
          
            # FIFTH: Update deployment image
            echo "Updating deployment image..."
            sed -i "s/\${DOCKERHUB_USERNAME}/${{ secrets.DOCKERHUB_USERNAME }}/g" deployment.yaml
          
            # SIXTH: Apply deployment and service
            echo "Applying deployment..."
            kubectl apply -f deployment.yaml
            echo "Applying service..."
            kubectl apply -f service.yaml
          
            # Check current status
            echo "Current deployment status:"
            kubectl get deployment perbaikiinaja-backend -n perbaikiinaja-prod || echo "Deployment not found yet"
            kubectl get pods -n perbaikiinaja-prod
          
            # Wait for deployment with better error handling
            echo "Waiting for deployment to be ready (timeout: 5 minutes)..."
            if kubectl wait --for=condition=available --timeout=300s deployment/perbaikiinaja-backend -n perbaikiinaja-prod; then
              echo "✓ Deployment successful!"
            else
              echo "⚠ Deployment timed out or failed. Checking status..."
              kubectl describe deployment perbaikiinaja-backend -n perbaikiinaja-prod
              kubectl get pods -n perbaikiinaja-prod
          
              # Get pod logs for debugging
              for pod in $(kubectl get pods -n perbaikiinaja-prod -o jsonpath='{.items[*].metadata.name}'); do
                echo "Logs for pod $pod:"
                kubectl logs $pod -n perbaikiinaja-prod --tail=50 || echo "Could not get logs for $pod"
              done
          
              # Don't exit with error - let's see if pods are running anyway
              echo "Checking if pods are running despite timeout..."
              RUNNING_PODS=$(kubectl get pods -n perbaikiinaja-prod --field-selector=status.phase=Running -o jsonpath='{.items[*].metadata.name}')
              if [ ! -z "$RUNNING_PODS" ]; then
                echo "✓ Some pods are running: $RUNNING_PODS"
              else
                echo "✗ No pods are running"
                exit 1
              fi
            fi
          
            # Final status check
            echo "Final deployment status:"
            kubectl get pods -n perbaikiinaja-prod -o wide
            kubectl get services -n perbaikiinaja-prod
          
            # Get service endpoint
            NODE_PORT=$(kubectl get service perbaikiinaja-backend-service -n perbaikiinaja-prod -o jsonpath='{.spec.ports[0].nodePort}')
            echo "Application should be accessible at: http://${{ secrets.PROD_EC2_HOST }}:${NODE_PORT}"
          EOF